### ISSUE TITLE
refactor commits statistics algrithm for stackalytics

### ISSUE THREAD

**Issue by bruceauyeung** [bruceauyeung/github-contrib-stats#12]
currently we use `stackalyticsDeviation` mechanism. but this is inherent incorrect. we should list commits on a repository ( https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository ) and filter them by user, date period, etc.

@xialonglee

**Comment by xialonglee** [comment]
i will try to introduce an api of github  to count the commits. It will count the commits as close as the `stackalyticsDeviation ` mechanism.
and try to introduce another api of github that can find a pull request from the `sha` of a commit, so that we can find out when the pr was merged.
it would be done in the next few days.
